export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_LOADING = 'USERS_LOADING';
export const GET_USERS_ERROR = 'USERS_ERROR';
export const GET_FILTERED_USERS = 'GET_FILTERED_USERS';
